language: generic
dist: xenial

before_install:
  # g++ 6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # Qt 5.11.2
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.2-xenial

  # Update
  - sudo apt-get -y update

install:
  # g++ 6
  - sudo apt-get install -y g++-6

  # OpenGL
  - sudo apt-get install libgl1-mesa-dev

  # Qt 5.11.2
  - sudo apt-get install -y qt511base

before_script:
  # g++ 6
  - export CC="gcc-6"
  - export CXX="g++-6"

  # Qt 5.11.2
  - QTDIR="/opt/qt511"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt511/bin/qt511-env.sh

  # Python 3.6
  - pyenv versions
  - pyenv global 3.6.7
  - ls -al $(python-config --prefix)/bin $(python-config --prefix)/lib $(python-config --prefix)/include

script:
  - mkdir build
  - cd build
  - |
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
      -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.6 \
      -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.6m.so \
      -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.6m \
      ..
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file vgc*.AppImage https://transfer.sh/vgc-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APvgcPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
